export class AccountPage {
	static emailField = '#email'
	static passwordField = '#password'
	static AccNav = '#navbarAccount'
	static LoginNav = '#navbarLoginButton'
	static loginBtn = '#loginButton'
	static loginGoogleBtn = '#loginButtonGoogle'
	static forgotPassword = '.forgot-pw'
	static newPassword = '#newPassword'
	static repeatNewPassword = '#newPasswordRepeat'
	static securityAnswerNew = '#securityAnswer'
	static resetBtn = '#resetButton'
	static checkboxRememberMe = '#rememberMe-input'
	static eyeHiddenBtn =
		'.mat-form-field-suffix > .mat-focus-indicator > .mat-button-wrapper'
	static notYetCustomerBtn = '#newCustomerLink'
	static emailReg = '#emailControl'
	static passwordReg = '#passwordControl'
	static repeatPasswordReg = '#repeatPasswordControl'
	static togglePasswordAdvice = '.mat-slide-toggle-thumb'
	static securityQuestion = '[name="securityQuestion"]'
	static listSecQuestion = '[role="listbox"]'
	static firstQuestion = '#mat-option-12 > .mat-option-text'
	static secondQuestion = '#mat-option-13 > .mat-option-text'
	static thirdQuestion = '#mat-option-14 > .mat-option-text'
	static forthQuestion = '#mat-option-15 > .mat-option-text'
	static fifthQuestion = '#mat-option-16 > .mat-option-text'
	static sixthQuestion = '#mat-option-17 > .mat-option-text'
	static securityAnswerReg = '#securityAnswerControl'
	static registerBtn = '#registerButton'
	static alreadyCustomerLink = '#alreadyACustomerLink'
	static logoutBtn = '#navbarLogoutButton'
	static confirmationMessage = '.mat-simple-snack-bar-content'
	static errorMessage = '.error'
}

export default AccountPage
